### PR TITLE
Feature implementation review request.

### PR DESCRIPTION
**Pull request by Meltrust**
### In this project we:

- Created a micro_reddit app for learning active record.
- Set up a linter
- Built models and migrations
- Coded using pair-programming
- Followed the git-flow rules.
- Encapsulated the code in classes and objects.
- Delivered the project with an organized folder structure.
- Wrote a descriptive readme file.
- Used the simplest solutions as possible, over the most complex ones.  Readability above all was always the goal.

Thanks for the review!

### CODE REVIEW

**Review by MahmoudBakr23 — COMMENTED** [review]
# **INVALID 🛑**

Hello there :)
I can see the effort made into this project, but I'm afraid I have to invalidate it due to disability to run the app locally because of this error:
```
error: invalid path 'app_screenshot.png:Zone.Identifier'
```
Git-Bksh__c_Users_mbakr_OneDrive_Desktop_micro_reddit 3_23

I think this specific file is causing a problem somehow!
Please try to fix that in order to get a review for your PR. So, good luck and happy coding 😊👨‍💻💻

**Comment by Meltrust** [comment]
Thanks, deleted the problematic file.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
/# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Meltrust and @ccobasi 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes 👇.
- [ ] `20210322221851_comments_model` causes the issue in migration please fix it.
- [ ] MIT license is missing in the README file.
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Meltrust** [comment]
Done! I corrected the migration file, cloned it in a new folder and it worked fine.  Thank you for the assistance.

**Comment by Meltrust** [comment]
Added license to readme

**Review by mke2111 — APPROVED** [review]
# STATUS: APPROVED ㊗️ 🟡 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval.

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Pull request merged**
